---
- name: get-config
  gather_facts: false
  hosts: all
  tasks:
    - name: Get config for IOS devices
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
          - show run
      register: result

    - name: Display the config
      debug: msg="{{ result }}"