---
collections:
  # Cisco collections
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.asa
  - name: cisco.nxos

  # Arista collections
  - name: arista.eos

  # Juniper collections
  - name: junipernetworks.junos

  # F5 BigIP collections
  - name: f5networks.f5_modules

  # Nokia SR OS collections (may not be available on Galaxy)
  # - name: nokia.sros

  # Aruba collections (may not be available on Galaxy)
  # - name: arubanetworks.arubaoss
